installed_widgets:
  - komodo.widgets:Number
  - komodo.widgets:StatusList
  - komodo.widgets:Graph
  - komodo.widgets:Gauge

dashboards:
  example:
    widgets:
       - type: Gauge
         data: random.number
         options:
           title: Users
           max: 1000
           threshold: 300
       - type: Number
         data: random.float
         options:
           title: Revenue
           prefix: $
           suffix: "k"
           backgroundColor: "#3498db"
       - type: StatusList
         data: statuses.status1
         options:
           title: Test
           suffix: " ms"
       - type: StatusList
         data: statuses.status2
         options:
           threshold: 50
           prefix: $
       - type: Number
         data: random.number2
       - type: Graph
         data: random.graph
         options:
           title: thing
  graph:
    widgets:
      - type: Graph
        data: random.graph
        options:
          title: aaa


checks:
  random:
    import_path: komodo.core_modules.example:RandomNumbers
  statuses:
    import_path: komodo.core_modules.example:RandomStatus
